### ISSUE TITLE
English

### ISSUE THREAD

**Issue by sschmid** [Rubentxu/Entitas-Java#1]
Hey Ruben,

great to see this active and up-to-date port of Entitas. Great work!
I'd suggest writing comments and commits in english as this will help other people to understand what you're working on and removes language barriers for future collaboration.

Keep it up! :)

**Comment by Rubentxu** [comment]
Thank you, the problem is that I understand very little English, and I do everything through the translator. But as soon as I finish certain things I want to do I will start to comment the code, even if I do not express myself very well.
